In [1]:
pwd

'C:\\Users\\rambu\\Python Scripts\\Milestone_3\\docker-project-template\\ift6758\\ift6758\\client'

In [3]:
from data_utils import fetch_data_by_api, get_play_by_play_by_game
from feature_eng_1 import get_engineered_df_by_game
import pandas as pd

In [11]:
data = fetch_data_by_api(2016020001)

Fetched 2016020001

In [12]:

list_of_plays = get_play_by_play_by_game(data)

df = pd.DataFrame( list_of_plays )

In [13]:
df.head(5)

,game_id,season,game_type,game_outcome,period_number,period_type,time_in_period,strength,event_type,shot_type,...,home_location,home_abrev,home_score,away_id,away_name,away_location,away_abrev,away_score,venue,venue_location
0,2016020001,20162017,2,OT,1,REG,01:11,NaN,shot-on-goal,wrist,...,Ottawa,OTT,5,10,Maple Leafs,Toronto,TOR,4,Canadian Tire Centre,Ottawa
1,2016020001,20162017,2,OT,1,REG,02:14,NaN,missed-shot,wrist,...,Ottawa,OTT,5,10,Maple Leafs,Toronto,TOR,4,Canadian Tire Centre,Ottawa
2,2016020001,20162017,2,OT,1,REG,02:53,NaN,shot-on-goal,wrist,...,Ottawa,OTT,5,10,Maple Leafs,Toronto,TOR,4,Canadian Tire Centre,Ottawa
3,2016020001,20162017,2,OT,1,REG,03:43,NaN,missed-shot,deflected,...,Ottawa,OTT,5,10,Maple Leafs,Toronto,TOR,4,Canadian Tire Centre,Ottawa
4,2016020001,20162017,2,OT,1,REG,04:01,NaN,shot-on-goal,wrist,...,Ottawa,OTT,5,10,Maple Leafs,Toronto,TOR,4,Canadian Tire Centre,Ottawa

In [14]:
df.columns

Index(['game_id', 'season', 'game_type', 'game_outcome', 'period_number',
       'period_type', 'time_in_period', 'strength', 'event_type', 'shot_type',
       'x', 'y', 'player_id', 'player_name', 'goalie_id', 'goalie_name',
       'zone_code', 'event_owner_team_id', 'event_owner_team_name', 'home_sog',
       'away_sog', 'home_defending_side', 'home_id', 'home_name',
       'home_location', 'home_abrev', 'home_score', 'away_id', 'away_name',
       'away_location', 'away_abrev', 'away_score', 'venue', 'venue_location'],
      dtype='object')

In [15]:
new_df = get_engineered_df_by_game(df)

In [16]:
new_df.head(5)

,game_id,season,game_type,game_outcome,period_number,period_type,time_in_period,strength,event_type,shot_type,...,away_score,venue,venue_location,is_goal,empty_net,x_mean_home,x_distance,distance_net,angle_deg,angle_rad
0,2016020001,20162017,2,OT,1,REG,01:11,NaN,shot-on-goal,wrist,...,4,Canadian Tire Centre,Ottawa,0,0,56.2,12,13.000000,22.619865,0.394791
1,2016020001,20162017,2,OT,1,REG,02:14,NaN,missed-shot,wrist,...,4,Canadian Tire Centre,Ottawa,0,0,56.2,37,38.078866,13.671307,0.238609
2,2016020001,20162017,2,OT,1,REG,02:53,NaN,shot-on-goal,wrist,...,4,Canadian Tire Centre,Ottawa,0,0,56.2,3,13.341664,77.005383,1.343997
3,2016020001,20162017,2,OT,1,REG,03:43,NaN,missed-shot,deflected,...,4,Canadian Tire Centre,Ottawa,0,0,56.2,17,17.000000,0.000000,0.000000
4,2016020001,20162017,2,OT,1,REG,04:01,NaN,shot-on-goal,wrist,...,4,Canadian Tire Centre,Ottawa,0,0,56.2,66,76.157731,29.931512,0.522403

In [17]:
new_df.shape

(98, 41)